# Identidad y enlaces del launcher de Aeldoria RPG

[ejs.app]
title = "Aeldoria Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/RyuTV/AeldoriaRPG"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/E2VFYPeA2W"

[ejs.settings]
sourceGithubLink = "https://github.com/RyuTV/AeldoriaRPG"
supportLink = "https://github.com/RyuTV/AeldoriaRPG/issues"

[ejs.welcome]
welcomeHeader = "BIENVENIDO A AELDORIA"
welcomeDescription = "Has sido invocado a un mundo dividido en pisos, territorios y culturas custodiados por poderosos Guardianes. Como Viajero, explorarás ciudades como Belmora, descubrirás antiguas amenazas y forjarás tu camino junto a otros aventureros. Supera cada piso si deseas encontrar el camino de regreso a tu mundo."
welcomeDescCTA = "Tu historia en Aeldoria comienza aquí."
